### ISSUE TITLE
Implement document API

### ISSUE THREAD

**Issue by pmig** [mkbouaziz/OrientR#5]
We need to support all document operations:

> Operations on documents by RID
> GET - HEAD - POST - PUT - DELETE - PATCH

For more information see http://orientdb.com/docs/2.1/OrientDB-REST.html#query
## Todos:
- [X] implement first working version
- [ ] implement fetchPlan
- [ ] implement updateMethod for PUT requests e.g. ?updateMode=full|partial]
- [ ] write documentation

**For PUT and PATCH:**
- [ ] result is text because of response plaintext content, needs to be converted to a named list
## Bugs:
- [ ] Big dataframes can be inserted / update / patched but you still receive a converting error of the result
- [ ] For some methods url encoding of the rid is necessary

**Comment by pmig** [comment]
currently working on it @mkbouaziz can you assign this to me?

**Comment by mkbouaziz** [comment]
I added you to the project as collaborator

**Comment by pmig** [comment]
RCurl doesn't support the patch method, so we need to use httr for the document api

It would be good to change the other requests as well. (in my opinion it's better maintained anyway)

If httr will do the job I'll create a followup ticket for switching to httr instead of RCrul. @mkbouaziz do you know about any complications?

**Comment by pmig** [comment]
Hi @mkbouaziz ,

I pushed a basic interface to the branch feature/issue-5

See the difference here:
https://github.com/mkbouaziz/OrientR/compare/feature/issue-5

I'm now waiting for review

**Comment by pmig** [comment]
@mkbouaziz Did you already have some time for feedback / code review?
@retrography Can you take a look in the code as well?

I'm really curious to get this merged asap and also get it merged with retrography/OrientR which is the official linked driver.

**Comment by mkbouaziz** [comment]
Hi @pmig ,
I will show what you have done , and answer you this night after work.

**Comment by mkbouaziz** [comment]
About R/orientDocument.R
- good, you have created all functions we need for REST api, but don't forget, every function has to be in a separated R file
- you have a mistake in line 116 , Delte -> Delete

So @pmig  correct these things and the we can accepte the pull request ;)

**Comment by pmig** [comment]
Hi @mkbouaziz 

Thanks for the feedback. I'll implement these changes. What's your opinion in chaning RCurl with httr?

**Comment by mkbouaziz** [comment]
hi @pmig , any news about OrientR ?

**Comment by pmig** [comment]
Hi,

still unsure about using httr. Should we refactor all others methods? Or should we refactor afterwards?

**Comment by mkbouaziz** [comment]
About using RCurl or httr, I think httr is enough for us, except for the performance side, and what time spend each methode in every package to do a request.

I haven't any idea about the best performance between both.

About refactoring methods, I think it will be best if we refactor afterwards.

You can choose any thing you find better Philip.

Best,

**Comment by pmig** [comment]
Ok I will finish up this ticket tomorrow and write a documentation and merge it back it master.

The next step would be to merge everything together with https://github.com/retrography/OrientR

**Comment by mkbouaziz** [comment]
Ok, create a pull request for a code review before merging, then we can try for the next step
